"""Correction de la relation projector du modèle Group

Revision ID: 2d45e7ce5349
Revises: d354d9c841d7
Create Date: 2026-01-26 17:07:11.602685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d45e7ce5349'
down_revision: Union[str, Sequence[str], None] = 'd354d9c841d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
