"""label_nest_plus_unique_lightmap_projector

Revision ID: 8cdac890e559
Revises: 3f4f399d2c3e
Create Date: 2026-01-27 15:55:10.994487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdac890e559'
down_revision: Union[str, Sequence[str], None] = '3f4f399d2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lightmap_projectors', 'label',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint(op.f('lightmap_projectors_label_key'), 'lightmap_projectors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lightmap_projectors_label_key'), 'lightmap_projectors', ['label'], postgresql_nulls_not_distinct=False)
    op.alter_column('lightmap_projectors', 'label',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
