"""ajout_du_modele_gelatine_et_relation_avec_lightmap_projector

Revision ID: a3190f468841
Revises: e29a2a7d8133
Create Date: 2026-01-27 15:05:46.903285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3190f468841'
down_revision: Union[str, Sequence[str], None] = 'e29a2a7d8133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gelatines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=False),
    sa.Column('is_diffuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('lightmap_projector_gelatine_association',
    sa.Column('lightmap_projector_id', sa.Integer(), nullable=False),
    sa.Column('gelatine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gelatine_id'], ['gelatines.id'], ),
    sa.ForeignKeyConstraint(['lightmap_projector_id'], ['lightmap_projectors.id'], ),
    sa.PrimaryKeyConstraint('lightmap_projector_id', 'gelatine_id')
    )
    op.drop_column('lightmap_projectors', 'gelatine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightmap_projectors', sa.Column('gelatine', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_table('lightmap_projector_gelatine_association')
    op.drop_table('gelatines')
    # ### end Alembic commands ###
