"""Initial migration

Revision ID: d354d9c841d7
Revises: 
Create Date: 2026-01-26 16:54:23.654873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd354d9c841d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lightmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['background_id'], ['backgrounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('eos_name', sa.String(length=80), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('projector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projector_id'], ['projectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eos_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lightmap_projectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('projector_id', sa.Integer(), nullable=False),
    sa.Column('lightmap_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z_level', sa.Integer(), nullable=False),
    sa.Column('angle', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('gelatine', sa.String(length=80), nullable=True),
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('universe', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lightmap_id'], ['lightmaps.id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ),
    sa.ForeignKeyConstraint(['projector_id'], ['projectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('group_projector_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('projector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['projector_id'], ['lightmap_projectors.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'projector_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_projector_association')
    op.drop_table('lightmap_projectors')
    op.drop_table('modes')
    op.drop_table('lightmaps')
    op.drop_table('projectors')
    op.drop_table('groups')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
