"""Ajout de is_led pour Projector

Revision ID: e29a2a7d8133
Revises: 2d45e7ce5349
Create Date: 2026-01-26 17:32:13.943460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29a2a7d8133'
down_revision: Union[str, Sequence[str], None] = '2d45e7ce5349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lightmaps', 'background_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # Add with server_default to satisfy existing rows, then drop default
    op.add_column(
        'projectors',
        sa.Column('is_led', sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.execute("UPDATE projectors SET is_led = false WHERE is_led IS NULL")
    op.alter_column('projectors', 'is_led', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectors', 'is_led')
    op.alter_column('lightmaps', 'background_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
